services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql/data

  db-setup:
    image: fabiang/go-sqlcmd
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      USER_PASSWORD: ${USER_PASSWORD}
    volumes:
      - ./sql/.init:/scripts
    command:
      - -S
      - db
      - -U
      - sa
      - -P
      - ${SA_PASSWORD}
      - -d
      - master
      - -v
      - DB_NAME=gofindag
      - -v
      - APP_USER=gofindag
      - -v
      - APP_PASSWORD=${USER_PASSWORD}
      - -i
      - /scripts/setup.sql

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: ./db_data
      o: bind